%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace.

% Auto-generated by MATLAB (R2025b) and Database Toolbox Version 25.2 on 26-Apr-2026 11:58:34
function[resultado] = consultaDato();

%% Make connection to database
conn = database('mysql2026Diario');


%Set query to execute on the database
query = ['SELECT ID_PRODUCTO_25, CANTIDAD_25, PRECIO_COSTO_25, PRECIO_UNITARIO_25 ' ...
    'FROM practicaparcial2.productos_25 WHERE ESTADO_25=1 ORDER BY ID_PRODUCTO_25 DESC'];

%% Execute query and fetch results
data = fetch(conn,query);

%% Close connection to database
close(conn)

%% Clear variables
clear conn query
if isstruct (data)
    resultado = struct2table(data);
elseif iscell(data)
    resultado = cellt2table(data);
else 
    resultado = data;
end